version: '3.9'

services:
  web:
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ".\\week1_docker\\php:/var/www/html"
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d