version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/vuln?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    volumes:
      - uploads_data:/app/src/main/webapp/uploads
      - static_uploads:/app/src/main/resources/static/uploads
      - downloads_data:/app/src/main/resources/downloads
    restart: always
    networks:
      - spring-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=vuln
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
  uploads_data:
  static_uploads:
  downloads_data:

networks:
  spring-network: